repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        types: [rst]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        types: [python]
        additional_dependencies: [
            flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
            flake8-docstrings, flake8-eradicate, flake8-print, flake8-rst-docstrings,
            flake8-todo, pep8-naming, pydocstyle,
        ]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc3
    hooks:
        -   id: doc8
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
