name: grfpy

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - anaconda-client
  - conda-build
  - conda-verify

  - r-grf
  - rpy2

  - click
  - jupyterlab
  - nbsphinx

  - numpy=1.16
  - pandas<=1.0.5

  - pdbpp
  - pytest
  - pytest-cov
  - pytest-xdist
    # - sphinx=2.4.4
    # - pydata-sphinx-theme>=0.3.0
    # - sphinxcontrib-bibtex
    # - fuzzywuzzy
    # - joblib
    # - cloudpickle
  - pip:
    - black
    - blackcellmagic
      # - bump2version
    - pre-commit
